version: '3.4'

networks:
  dev:
    driver: bridge

services:
  wheels-n-deals:
    image: docker.io/library/wheelsndeals
    depends_on:
      - "app_db"
    container_name: wheelsndeals-services
    ports:
      - "8088:80"
    build:
      context: ./Wheels-n-Deals.API
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=User ID=postgres;Password=root;Server=app_db;Port=5432;Database=AutoSiteDb;IntegratedSecurity=true;Pooling=true;
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - dev
  app_db:
    image: postgres:latest
    container_name: app_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=AutoshopSiteDb
    ports:
      - "5433:5432"
    restart: always
    volumes:
      - app_data:/var/lib/postgresql/data
    networks:
      - dev
  angular_app:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: angular-app
    working_dir: /client
    ports:
      - "4200:4200"
    networks:
      - dev
volumes:
  app_data: